---
- name: deploy website
  hosts: all
  become: yes
  tasks:
    - name: update packages and install nginx
      ansible.builtin.apt:
        name: nginx
        update_cache: yes
        state: present
    - name: enable and start nginx service
      ansible.builtin.systemd_service:
        name: nginx
        enabled: yes
        state: started
       